---
title: 'GSE 520: Problem Set #2'
author:
- Rus Adamovics-Davtian
- Christopher Almacen
output: html_document
---

### Question 1

Suppose someone proposes that the quantity of movies demanded is related to price and income by the linear equation, 
$$quantity = 120 - 9.8 price + .03 income$$

a. What is the interpretation of the number $120$ in the equation above?

>**Solution:**  
We can interpret the intercept $120$ as the expected mean quantity given that both price and income are zero.

b. What is the interpretation of the number $9.8$ in the equation above?  Is this a marginal effect?  If so, of what?

>**Solution:** 
Adjusting for income, we can expect on average a 9.8 unit decrease in quantity for every additional dollar increase in price. Yes, this is a marginal effect. We are finding the marginal effect of a one unit increase in price on quantity, treating income as a constant (held fixed). 

c. What is the demand for movies if $price=15$ and $income=200$?  What does this suggest about using linear functions to describe demand curves?

>**Solution:**  
If price = 15 and income = 200, then 
\begin{align*}
demand = & 120 - 9.8*(15) + 0.03*(200)\\
demand = & -21
\end{align*}

>Using linear functions to describe demand curves suggest that the effect of only price or only income on demand is always constant. This is typically not the case in the real world as individuals with large income may demand exponentially more than individuals with low income keeping price constant. 

### Question 2

Let $prate$ be the fraction of employees participating in a 401K plan (401K's are employer sponsored retirement savings plans).  Let $mrate$ be the match rate, for example if a person's salary is \$100K and the match rate is 4.07, then the employer will match the employees 401K contribution up to the amount of \$4,070.  Suppose the function relating $mrate$ to $prate$ is described by 
$$prate = 83.1 + 5.9(mrate)$$

a. How do you interpret the intercept?
  
>**Solution:**
We can interpret the intercept $83.1$ as the expected mean percentage of employees participating in a 401k given that the employer's match rate is zero.

b. Do the parameters of this function appear to be the `right' sign, i.e. would it make more sense if the coefficient on $mrate$ was negative?

>**Solution:**  
Yes, it makes sense that the coefficient on $mrate$ is positive, not negative. As the match rate increases, we expect more people to participate in a 401k. Companies matching a higher percentage of salary means employees will have more money in their 401k which would entice people to join.   

c. Consider a quadratic function 
$$prate = 78.6 + 17(mrate) - 3.2(mrate^2)$$
Take the derivative of this function with respect to $mrate$ and show that the marginal effect of $mrate$ on $prate$ depends on the current level of $mrate$.

>**Solution:**  
\begin{align*}
\frac{dprate}{dmrate} = 17 - 6.4(mrate)
\end{align*}

d. Sketch the general shape of the quadratic function with $prate$ on the y-axis and $mrate$ on the x-axis.  Use the code below (see what it looks like in the HTML) to upload your sketch.


>```{r pressure, echo=FALSE, out.width = '50%'}
library(ggplot2)
mrate <- seq(0, 8, 0.1)
prate <- 78.6 + 17*(mrate) - 3.2*(mrate^2)
df <- data.frame(seq(0, 8, 0.1), 78.6 + 17*(mrate) - 3.2*(mrate^2))
ggplot(data = df, aes(x = mrate, y = prate)) + geom_line(size = 2) + 
  ggtitle("Plot of Y = 78.6 + 17*(mrate) - 3.2*(mrate^2)")
```

**Solution:**  

e. Given the quadratic function above, at what value of $mrate$ does increasing $mrate$ actually begin decreasing $prate$?

>**Solution:**  
\begin{align*}
\frac{dprate}{dmrate} = & 17 - 6.4(mrate) = 0\\
17 = & 6.4(mrate)\\
mrate = & 17/6.4 = 2.65625
\end{align*}

### Question 3

Next let's consider interpreting functions with the natural log. Suppose that the one way ticket price, $fare$, for an airline ticket is a function of distance (in 100 miles), $dist$, through the equation:
$$\ln(fare) = a + b \cdot dist$$
with
$$\ln(fare) = 4.666 +  0.043(dist)$$

a. How do you interpret the intercept?  Is it of any use?

>**Solution:**  
We can interpret the intercept as the expected mean log of ticket price for a one-way flight when the distance traveled is zero miles. However, it is not of any use since it is on a log scale and flights are never zero miles long. In this case, we would expect the ticket price on average to be... 
$$e^{4.666} = $106.27$$


b. Compute the $\ln(fare)$ of a flight that is 100 miles (i.e., $dist=1$).  What is the price in dollars for a flight that is 100 miles?

>**Solution:** 
\begin{align*}
\ln(fare) = & 4.666 +  0.043(1) = 4.709\\
fare = & e^{4.709} = $110.94
\end{align*}

c. Compute the actual fare in dollars for a flight that is 200 miles.  What unit increase in distance is this compared to the previous question.  What percent increase is this in the fare?  Is this approximately 4.3\%?

>**Solution:**
\begin{align*}
\ln(fare) = & 4.666 +  0.043(2) = 4.752\\
fare = & e^{4.752} = $115.82\\
increase = & (115.82 - 110.94) / (110.94) = 0.044\\
\end{align*}

> This represents a one unit increase in distance compared to the previous question. Yes, each additional one unit increase in distance results in approximately a 4.3% change increase in fare price.   

d. Let's formalize this with calculus.  Re-write $fare = \exp(4.666  + 0.043 dist)$.  Take the derivative of this with respect to $dist$ and divide both sides by $fare$.  Show 
$$0.043 = \dfrac{\partial fare/ fare}{\partial dist} = \dfrac{\Delta fare/ fare}{\Delta dist} = \dfrac{\%\Delta fare}{\Delta dist}$$
In a log-level function the coefficient on $dist$ indicates the percentage change in $fare$ given a unit change in distance.  Thus if $dist$ increases by 1 unit (100 miles) the fare will increase by (approximately) 4.3\%

>**Solution:** 
\begin{align*}
0.043 = & \frac{dfare / fare}{ddist} = \dfrac{\Delta fare/ fare}{\Delta dist} = \dfrac{\%\Delta fare}{\Delta dist}\\
0.043 = & \frac{e^{4.666  + 0.043*dist} * 0.043}{fare}\\
0.043 = & \frac{fare * 0.043}{fare}\\
0.043 = & 0.043
\end{align*}

### Question 4

Here is an alternative function with natural logs that relates one way ticket price, $fare$, for an airline ticket to distance (in 100 miles), $dist$, through the equation:
$$fare = a + b \cdot \ln(dist)$$
where
$$fare = 41 + 66\ln(dist)$$
a. How does this function differ from the one in the previous problem

>**Solution:**  
The function previously was a log-level function (natural log transformation on response variable fare, no transformation on explanatory variable distance), where a level change in distance corresponds to a constant 100*(distance coefficient) percent change in fare. This function differs in that it is a level-log function (no transformation on fare, natural log transformation on distance). In this case, a 1% change in distance corresponds to a (distance coefficient) / 100 level change in fare.  

b. Let $fare =  41+66\ln(dist)$.  We would like to understand how to interpret the coefficient on $\ln(dist)$ (i.e., 66).  Take the derivative of the equation with respect to $dist$ and divide both sides by $1/dist$, show 
$$66 = \dfrac{\partial fare}{\partial dist/dist}= \dfrac{\Delta fare}{\Delta dist/dist} = \dfrac{\Delta fare}{\% \Delta dist}$$
This reads, if the denominator changes by 1 unit (a 100\% increase in distance), the dependent variable $fare$ will increase (approximately) by \$66.  This is a level-log function

>**Solution:**  
\begin{align*}
fare = & 41+66\ln(dist)\\
\frac{dfare}{ddist} = & \frac{66}{dist}\\
\frac{dist}{1} * \frac{dfare}{ddist} = & \frac{66}{dist} * \frac{dist}{1}\\
66 = & \frac{dfare}{ddist / dist} = \dfrac{\Delta fare}{\Delta dist / dist} = \dfrac{\Delta fare}{\%\Delta dist}
\end{align*}

c. Your calculation above suggests that if $dist$ increases by 100\%, $fare$ should increase by \$66.  Check to see if this is true by comparing the actual $fare$ of a flight that is 400 miles to a flight that is 200 miles.

>**Solution:**
A 100% change in distance corresponds to a ((distance coefficient) / 1) level change in fare where distance coefficient equals 66. Therefore, we would expect a 100% change in distance to lead to an approximate increase in fare of $66/1 = $66.0$  
$$ fare_d = [44 + 66*\ln(400)] - [44 + 66*\ln(200)] = $45.75 $$

d. If a 100\% change in $dist$ leads to an approximate increase in fare of \$66, what would you expect the approximate increase in $fare$ to be if $dist$ increased by 10\%? Check to see if this is a good approximation by comparing the actual fare difference for a flight that is 220 miles to a flight that is 200 miles?

>**Solution:**
A 10% change in distance corresponds to a ((distance coefficient) / 10) level change in fare where distance coefficient equals 66. Therefore, we would expect a 10% change in distance to lead to an approximate increase in fare of $66/10 = $6.6$   
$$fare_d = [44 + 66*\ln(220)] - [44 + 66*\ln(200)] = $6.29$$

e. If a 100\% change in $dist$ leads to an approximate increase in fare of \$66, what would you expect the approximate increase in $fare$ to be if $dist$ increased by 1\%? Check to see if this is a good approximation by comparing the actual fare difference for a flight that is 202 miles to a flight that is 200 miles?

>**Solution:**
A 1% change in distance corresponds to a ((distance coefficient) / 100) level change in fare where distance coefficient equals 66. Therefore, we would expect a 1% change in distance to lead to an approximate increase in fare of $66/100 = $0.66$   
$$fare_d = [44 + 66*\ln(202)] - [44 + 66*\ln(200)] = $0.657$$

f. What can you conclude about the percentage change interpretation on the coefficient on a natural log variable.  When is it a good approximation, when considering small percentage changes or large percentage changes?

>**Solution:**
It is a good approximation when considering small percentage changes, not large percentage changes. 

### Question 5

Consider the log-log function where $fare$, for an airline ticket relates to distance (in 100 miles), $dist$, through the equation:
$$\ln(fare) = a + b \cdot \ln(dist)$$
Where
$$\ln(fare) = 4.25 + 0.40 \ln(dist)$$
We would like to understand how to interpret the coefficient on $\ln(dist)$ (i.e., 0.40). Prove that this function can be interpreted as a 10\% increase in $dist$ leads to a 4\% increase in fare.

a. Begin by writing $fare = e^{4.25}dist^{0.40}$ and taking the derivative with respect $dist$ and reworking to show that 
$$.40 = \dfrac{\partial fare/fare}{\partial dist/dist} = \dfrac{\Delta fare/fare}{\Delta dist/dist} = \dfrac{\% \Delta fare}{\% \Delta dist}$$

>**Solution:**  
\begin{align*}
\epsilon_{fare, dist} = & \frac{dfare}{ddist} * \frac{dist}{fare}\\
\epsilon_{fare, dist} = & (0.4e^{4.25} * dist^{-0.6}) * \frac{dist}{(e^{4.25} * dist^{0.4})}\\
\epsilon_{fare, dist} = & \frac{0.4e^{4.25}*dist^{0.4}}{e^{4.25}*dist^{0.4}}\\
\epsilon_{fare, dist} = & 0.4
\end{align*}

b. Since the log-log function is about percentages, let's now show that this implies that the units do not matter.  Suppose that instead of letting $dist$ taking units of 100 miles, we wrote the same function except that $dist$ takes units of miles.  Is it surprising that this function takes the form:
$$\ln(fare) = 2.40 + 0.40 \ln(dist)$$
Show that if we have $\ln(y) = a + b \ln(x)$ and $\ln(y) = a' + b' \ln(100 \times x)$ that $b=b'$ however $a \neq a'$.  (hint: you need to use the properties of $\ln$ that $\ln(a \times x) = \ln(a) + \ln(x)$)

>**Solution:**
\begin{align*}
a + b\ln(x) = & a^{'} + b^{'}\ln(100 + x)\\
a + b\ln(x) = & a^{'} + b^{'}\ln(100) + b^{'}\ln(x)
\end{align*}

### Question 6

There are two types of apples, organic (eco) and conventional (reg).  An individual demand equation relating the amount of eco apples purchased in pounds ($ecolbs$) as a determined by the individual's education ($educ$) and price of eco apples and regular apples is 
$$ecolbs = 1.34 + 0.04(educ) + 3.00(regprc) -2.87(ecoprc)$$

a. Is it surprising that if the price of regular apples increases that the demand for eco apples increases?

>**Solution:**
No, since regular apples and organic apples are considered substitute goods. If the price of one good increases, then the demand of that good's substitute increases.   

b. What is the marginal effect of education on demand for eco apples?  Would you say individuals with more education purchase more eco apples compared to people with lower levels of education holding fixed price?

>**Solution:**  
$$ \frac{\partial ecolbs}{\partial educ} = 0.04$$
Adjusting for price of organic and regular apples, we can expect on average a constant 0.04 lb increase in quantity demanded of eco apples for every one additional year of education. Which means individuals with more education on average purchase slightly more eco apples than individuals with less education. 

c. Consider an alternative function that includes an interaction
$$ecolbs = 2.16 - 0.02(educ) + 3.00(regprc) -3.64(ecoprc) + 0.05(educ\times ecoprc)$$
Show that with this function the marginal effect of price depends on the level of education.  Who is more responsive to price, individuals with high or low levels of educations?

>**Solution:**  
$$ \frac{\partial ecolbs}{\partial ecoprc} = -3.64 + 0.05(educ)$$
Individuals with lower levels of education are more responsive to the price of organic apples. 

d. Given the function with interactions.  Holding fixed the price of regular apples, find the range of prices for eco apples where a person with 12 years of education will buy more eco apples than a person with 13 years of education.

>**Solution:**  
\begin{align*}
-0.02*(12) - 3.64*(ecoprc) + 0.05*(12*ecoprc) > & -0.02*(13) - 3.64*(ecoprc) + 0.05*(13*ecoprc)\\
-0.24 - 3.64*(ecoprc) + 0.6*(ecoprc) > & -0.26 - 3.64*(ecoprc) + 0.65*(ecoprc)\\
0.02 > & 0.05*(ecoprc)\\
\frac{0.02}{0.05} > & \frac{ecoprc}{0.05}\\
ecoprc < & $0.40
\end{align*}

e. Using this function, plot the relationship between eco pounds demanded and education for low price of eco-apples \$0.90 and a high price of eco-apples \$1.30, assuming the price of regular apples is \$0.90 in both situations.  Hint: here you are plotting $ecolbs$ on the y-axis against $educ$ on the x-axis holding fixed eco-price and regular apple price.  Does this plot illustrate which group of buyers, high education v. low education are most sensitive to price changes of eco-apples?

>**Solution:**  
```{r, echo=FALSE, out.width = '50%'}
regprc <- 0.9
educ <- 0:100
ecoprc_low <- 0.9
ecoprc_high <- 1.3
ecolbs_low <- 2.16 - 0.02*(educ) + 3*(regprc) -3.64*(ecoprc_low) + 0.05*(educ*ecoprc_low)
ecolbs_high <- 2.16 - 0.02*(educ) + 3*(regprc) -3.64*(ecoprc_high) + 0.05*(educ*ecoprc_high)
low <- data.frame(regprc, educ, ecoprc_low, ecolbs_low)
high <- data.frame(regprc, educ, ecoprc_high, ecolbs_high)

ggplot() + 
  geom_line(data = low, aes(educ, ecolbs_low, color = "Low"), size = 1.5) + 
  geom_line(data = high, aes(educ, ecolbs_high, color = "High"), size = 1.5) + xlab("Years of Education") + ylab("Ecolbs (Demand)") + 
  scale_color_manual(name = "EcoPrc", values = c("Low" = "blue", "High" = "red")) + ggtitle("Red: 2.16 - .02(educ) + 3(0.9) -3.64(1.3) + .05(educ*1.3)\nBlue: 2.16 - .02(educ) + 3(0.9) -3.64(0.9) + .05(educ*0.9)")
```

Holding fixed the regular price of apples, it seems that the effect of education on demand of organic apples depends on the (low or high) price of organic apples. Individuals with lower education are even more sensitive to price changes (from low to high) than individuala with higher levels of education. That is seen by the red line being steeper (larger slope) than the blue line (smaller slope).      

### Question 7

a. Suppose the number of applicants to a university ($apps$) is a function of whether in the previous year the University participated in a bowl game ($bowl$), whether the mens' basketball team was conference champs, $btitle$, or whether the mens' basketball team was in the final four $finfour$.  Each of these variables $bowl$, $btitle$, and $finfour$ is an indicator variable, taking a value of 1 if true and zero otherwise.

    What is the meaning of the intercept in the function below
$$apps = 9677.14 + 1423.23(bowl) + 410.16(btitle) + 2952.49(finfour)$$

>**Solution:**  
We can interpret the intercept as the expected mean number of applicants to university (apps) this year given that the university last year did not participate in a bowl game, did not participate in the men's basketball final four, and were not men's basketball conference champions.

b. Monthly US presidential approval ratings for the years 2001 to 2007 can be described by the following equation
$$ approve = b_0 + b_1 rgasprice + b_2 katrina + b_3 iraqinvade + b_4 sep11$$
Where $rgasprice$ is real gas price, $katrina$ is an indicator variable if it was the month of hurricane Katrina, $iraqinvade$ is an indicator if it was the month the US invaded Iraq, and $sep11$ is an indicator if the month was September 2001.

    In fact assume the relationship can be precisely defined as
$$ approve = 101.25 - 0.50 rgasprice + 14.76 katrina + 6.75 iraqinvade + 22.54 sep11$$
What is the meaning of the intercept in the function above?

>**Solution:**  
We can interpret the intercept as the average monthly US presidential approval rating (101.25) when the time of the year is not September 2001, and the month of the year is not the same month as when the US invaded Iraq, and the month of the year is not the same month as when Hurrican Katrina occured, and that the gas price at the time is zero. 