---
title: 'GSE 520: Problem Set #1'
author: 
  - "Rus Adamovics-Davtian"
  - "Adam Gockel"
  - "Russell Mcintosh"
output: html_document
---

### Question 1

Consider the equation $y = \beta_0 + \beta_1 x_1 + \beta_2 x_2$ 

a. Add an additional variable $x_3$ multiplied by $\beta_3$ to the equation (write the entire expression below).

>**Solution:**  
$y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3$

b. Change the $\beta$'s in the equation above to $\alpha$'s (write the new expression below).

>**Solution:**   
$y = \alpha_0 + \alpha_1 x_1 + \alpha_2 x_2 + \alpha_3 x_3$

### Question 2

Consider the matrix
\begin{align*} x = \left[
  \begin{matrix}
  3 & 1 & 1 \\
  1 & 2 & -1 \\
  2 & -1 & 4
  \end{matrix} \right]
\end{align*}

a. Write the R code to create this matrix.  Call it `x' and use the command ``print(x)`` to show that you created it correctly.  

>**Solution:**  
>```{r}
x <- matrix(c(3, 1, 1, 1, 2, -1, 2, -1, 4), ncol=3, byrow = TRUE)
print(x)
```


b. What is the inverse of the matrix above?  

>**Solution:**    
>```{r}
x_t <- t(x) 
print(x_t)
```

c. Is the inverse of the transpose of this matrix equal to the transpose of the inverse of this matrix?

>**Solution:**    
>```{r}
x_t_inv <- solve(t(x)) 
print(x_t_inv)
x_inv_t <- t(solve(x)) 
print(x_inv_t)
print("Yes, the inverse of the transpose is equal to the transpose of the inverse.", quote =F)
```
\

d. Prove that that the transpose of an inverse is equal to the inverse of the transpose (i.e., $(A^{-1})' = (A')^{-1}$).  You should use the align environment to show each step of your proof.


>**Solution:** 
Since A is an invertible matrix, 
\begin{align*}
A^{-1}*A = & A*A^{-1} = I\\   
(A^{-1}*A)^T = & (A*A^{-1})^T = I^T = I\\
A^T*(A^{-1})^T = & (A^{-1})^T*A^T = I\\
(A^{-1})^T = & (A^T)^{-1}
\end{align*}

### Question 3

Consider the following matrix products,
\begin{align*}
(X'X) = \left[
\begin{matrix}
4 & 46 \\
46 & 534
\end{matrix} \right]
\qquad 
(X'Y)= \left[
\begin{matrix}
12.7 \\
146.4
\end{matrix} \right] 
\end{align*}

Use **R** to calculate the value of $(X'X)^{-1}X'Y$.

>**Solution:**  
>```{r}
x_inv_x <- matrix(c(4, 46, 46, 534), ncol = 2, nrow = 2)
x_inv_y <- matrix(c(12.7, 146.4), ncol = 1, nrow = 2)
print(solve(x_inv_x) %*% x_inv_y)
```

### Question 4

Use the data ``airfare.RData`` to answer the following.  This data contains information on airlines routes in the US from 1997-2000.  In includes information like the average fare of the route and the distance of the route, as well as the fraction of flights on that route concentrated with a single carrier.

a. What is the minimum flight distance in the data set?

>**Solution:**   
>```{r}
airfare <- load("C:/Users/rusla/OneDrive/GSE_520/R Data/airfare.RData")
print(min(data$dist))
```

b. What is the average fare in the data set?

>**Solution:**   
>```{r}
print(mean(data$fare))
```

c. What is the average fare for 1998 in the data set?

>**Solution:**   
>```{r}
print(mean(data[data$year == 1998,"fare"]))
```

d. Many airline routes are only served by a single carrier, giving them potentially large market power to control prices.  What fraction of the markets in the data set have more than 90% of flights served by a single carrier?

>**Solution:**   
>```{r}
print(round(nrow(data[data$bmktshr > 0.9,]) / nrow(data), 4))
```
