---
title: 'GSE 520: Problem Set #1'
author: 
  - "Student Name 1"
  - "Student Name 2 (delete if only one student or add more if more than two)"
output: html_document
---

### Question 1

Consider the equation $y = \beta_0 + \beta_1 x_1 + \beta_2 x_2$ 

a. Add an additional variable $x_3$ multiplied by $\beta_3$ to the equation (write the entire expression below).

**Solution:**  

b. Change the $\beta$'s in the equation above to $\alpha$'s (write the new expression below).

**Solution:**  

### Question 2

Consider the matrix
\begin{align*} x = \left[
  \begin{matrix}
  3 & 1 & 1 \\
  1 & 2 & -1 \\
  2 & -1 & 4
  \end{matrix} \right]
\end{align*}

a. Write the R code to create this matrix.  Call it `x' and use the command ``print(x)`` to show that you created it correctly.  

**Solution:**  

b. What is the inverse of the matrix above?  

**Solution:**  


c. Is the inverse of the transpose of this matrix equal to the transpose of the inverse of this matrix?

**Solution:**  

d. Prove that that the transpose of an inverse is equal to the inverse of the transpose (i.e., $(A^{-1})' = (A')^{-1}$).  You should use the align environment to show each step of your proof.

**Solution:**  

### Question 3

Consider the following matrix products,
\begin{align*}
(X'X) = \left[
\begin{matrix}
4 & 46 \\
46 & 534
\end{matrix} \right]
\qquad 
(X'Y)= \left[
\begin{matrix}
12.7 \\
146.4
\end{matrix} \right] 
\end{align*}

Use **R** to calculate the value of $(X'X)^{-1}X'Y$.

**Solution:**  

### Question 4

Use the data ``airfare.RData`` to answer the following.  This data contains information on airlines routes in the US from 1997-2000.  In includes information like the average fare of the route and the distance of the route, as well as the fraction of flights on that route concentrated with a single carrier.

a. What is the minimum flight distance in the data set?

**Solution:** 

b. What is the average fare in the data set?

**Solution:** 

c. What is the average fare for 1998 in the data set?

**Solution:** 

d. Many airline routes are only served by a single carrier, giving them potentially large market power to control prices.  What fraction of the markets in the data set have more than 90% of flights served by a single carrier?

**Solution:** 

